<template>
  <v-card style="margin: 40px; padding: 40px">
    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Stok Kodu/Barkod:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Ürün Adı:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Tarih:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field
          variant="outlined"
          @click="datePickers = !datePickers"
          v-model="dateFormat"
          v-show="!datePickers"
        />

        <v-date-picker
          show-adjacent-months
          v-model="date"
          v-show="datePickers"
        />

        <v-btn
          :disabled="loading"
          style="margin: 0 24px; width: 316px; min-width: 316px"
          plain
          @click="dateClose"
          v-show="datePickers"
        >
          Kapat
        </v-btn>
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Kategori:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-select
          clearable
          :items="Object.keys(items)"
          variant="outlined"
          v-model="selectItemKey"
          @click="itemValuesFunction"
        />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Alt Kategori:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-select
          clearable
          variant="outlined"
          @click="itemValuesFunction"
          :items="itemValues"
          v-model="selectItemValue"
        />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Tedarikçi:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Marka:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Miktar:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Birim:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>

    <v-row style="margin: 10px" align="center">
      <v-col cols="2" style="padding: 0">
        <v-list-subheader style="padding-inline-end: 0">
          Birim Fiyat:
        </v-list-subheader>
      </v-col>

      <v-col cols="10" style="padding: 0">
        <v-text-field variant="outlined" />
      </v-col>
    </v-row>
  </v-card>
</template>

<script>
export default {
  data() {
    return {
      date: null,
      dateFormat: null,
      datePickers: false,
      items: {
        "Meyve & Sebze": {
          Meyve: [
            "Reyondan",
            "Verita",
            "Excelente",
            "Gürkan",
            "Del Monte",
            "Osmaniye",
            "Emsal",
            "M Life",
            "Genuine Coconut",
          ],
          Sebze: [
            "Reyondan",
            "Si&Ha",
            "Gurme212",
            "Eurofresh",
            "Dünya Hayat",
            "Garliko",
            "Agrotalya",
            "Yurtalan",
            "Canbaş",
            "Beyköy",
            "Verita",
            "Migros",
            "Tasconi",
            "Aressa",
          ],
          "Yetiştirme Kiti": ["Osmanlı Bahçesi", "Reyondan", "Eden Zirai"],
        },
        "Et, Tavuk & Balık": {
          "Kırmızı Et": [
            "Reyondan",
            "Uzman Kasap",
            "Pınar",
            "Superfresh",
            "Torku",
            "Gurvita",
            "Eral Et",
            "Tire",
            "Hasek",
            "Zel",
            "Orvital",
            "Migros",
            "Tire Süt Kooperatifi",
            "Erşan",
            "Eral",
          ],
          "Beyaz Et": [
            "Gedik",
            "Banvit",
            "Beypiliç",
            "Şenpiliç",
            "Erpiliç",
            "Bolez",
            "Gözde",
            "Bolca",
            "Lezita",
            "Orvital",
            "Ant Bahar",
            "İzmir",
            "Reyondan",
            "Gurvita",
          ],
          "Balık ve Deniz Mahsülleri": [
            "Reyondan",
            "Balık Dünyası",
            "Dardanel",
            "Kocaman",
            "Migros",
            "Pınar",
            "Red Tiger",
            "Conker",
            "Admirals",
            "Gusto",
            "Leroy",
            "Fish Point",
          ],
          "Et Şarküteri": [
            "Polonez",
            "Pınar",
            "Namet",
            "Erşan",
            "Apikoğlu",
            "Maret",
            "Başyazıcı",
            "Migros",
            "Yayla Türk",
            "Torku",
            "Aytaç",
            "Fümeci",
            "Özlem",
            "Banvit",
            "Reyondan",
            "Cumhuriyet Sucukları",
            "Şahin",
            "Fulya",
            "Altın Dana",
            "Yayla",
            "Altın",
            "Keskinoğlu",
            "Laz Kızı",
            "Seçme",
          ],
        },
        "Kahvaltılık & Süt Ürünleri": {
          Süt: [
            "İçim",
            "Pınar",
            "Fomilk",
            "Alpro",
            "Sek",
            "Danone",
            "Nilky",
            "Nestle",
            "VeganMilk",
            "Torku",
            "Dimes",
            "Activia",
            "Dulce De Leche",
            "Nesquik",
            "M Life",
            "Baltalı",
            "Efeler Çiftliği",
            "Orvital",
            "Alpimilk",
            "Elta Ada",
            "Milupa",
          ],
          Peynir: [
            "Tahsildaroğlu",
            "Pınar",
            "Bahçıvan",
            "İçim",
            "Ariste",
            "Muratbey",
            "La Vache Qui Rit",
            "Sek",
            "Taciroğlu",
            "President",
            "Doğruluk",
            "Altınkılıç",
            "Torku",
            "Elta Ada",
            "Hasmandıra",
            "Onsüt",
            "Kiri",
            "Golden Dutch",
            "Baltalı",
            "Ünal",
            "G.C. Gıda",
            "Akpınar",
            "Ünal Çiftliği",
            "Fomilk",
            "Lente",
            "Sütbon",
            "Ekici",
            "Milgo",
            "Anadolu Lezzetleri",
            "Laz Kızı",
            "Frico",
            "Cebir",
            "Veggy",
            "Sütaş",
            "Özışık",
            "Yardımcı",
            "Teksüt",
            "Biogurme",
            "P.E. 810",
            "Bergen",
            "Yeşil Kozan",
            "Karper",
            "Onur",
            "Primavera",
            "Koop",
            "Tire",
            "Orvital",
            "Clearspring",
            "Lactima",
            "Cebel",
            "Tire Süt Kooperatifi",
            "Alberto Di Centa",
            "Mandalinn",
            "Grandor",
            "Cibus",
            "Bergaz",
            "Gökçebayır",
            "Gündoğdu",
            "F.G",
            "Kervan",
            "Reyondan",
            "Peysan",
            "Philadelphia",
            "Savak",
            "Mersoy",
            "Kırıtaklar",
            "Cihanser",
            "Güneydoğu",
            "Efeler Çiftliği",
            "Meriç",
          ],
          Yoğurt: [
            "Activia",
            "Eker",
            "Danone",
            "İçim",
            "Sütaş",
            "Sek",
            "Arslan",
            "Pınar",
            "Elta Ada",
            "Torku",
            "Danino",
            "Tire Süt Kooperatifi",
            "Ateşoğlu",
            "Danem",
            "Nilky",
            "Belkıs Çiftliği",
            "Velioğlu",
          ],
          Tereyağı: [
            "Sek",
            "İçim",
            "Polonezköy",
            "S.S. Tire Organik Gıda Kooperatifi",
            "Laz Kızı",
            "Sütaş",
            "Pınar",
            "Tahsildaroğlu",
            "Ekici",
            "Kurpu",
            "Yörük Çiftliği",
            "Enka",
            "Elta Ada",
            "Kanlıca",
            "Hasmandıra",
            "Tire Süt Kooperatifi",
          ],
          Margarin: ["Teremyağ", "Becel", "Sana", "Bizim", "Sabah", "Lurpak"],
          Yumurta: [
            "Yumurtacım",
            "Coşkun",
            "Doğalım",
            "Raya",
            "Flotty",
            "Güres",
            "Naturaköy",
            "Orvital",
            "M Life",
            "Kor",
            "Green Ranch",
            "Gürata",
            "Tire",
            "Ordu Yumurta Üreticileri Birliği",
          ],
          Zeytin: [
            "Fora",
            "Marmarabirlik",
            "Cem Zeytin",
            "Zertum",
            "Cem",
            "Komili",
            "Adra",
            "Öncü",
            "Nutruit Olipop",
            "İlyada",
            "Bağcı",
            "Gürağaç",
            "Çukurbahçe",
            "Taneli",
            "Marmara Birlik",
            "Seleköy",
            "Oli Black",
          ],
          "Sütlü Tatlı ve Krema": [
            "Eker",
            "Dr.Oetker",
            "Eti",
            "Danette",
            "Kinder",
            "Fo",
            "Sek",
            "Pınar",
            "Pakmaya",
            "İçim",
            "Tikveşli",
            "Kenton",
            "Altın",
            "Oreo",
            "President",
            "Hulala",
            "Belkıs Çiftliği",
            "Milka",
            "Velioğlu",
            "Danissimo",
            "Danone",
            "Kısmet",
            "Green Way",
          ],
          Kahvaltılıklar: [
            "Balparmak",
            "Koska",
            "Yenigün",
            "Eti",
            "Patiswiss",
            "Beeo",
            "Kellogg's",
            "Tamek",
            "M Life",
            "Torku",
            "Nesquik",
            "Tat",
            "Nestle",
            "Fiskobirlik",
            "Sarelle",
            "Nesfit",
            "Anavarza",
            "Anadolu Lezzetleri",
            "Fellas",
            "Nustil",
            "Nut Master",
            "Züber",
            "Jif",
            "Fitnut",
            "City Farm",
            "Kühne",
            "Dr.Oetker",
            "Reyondan",
            "Penguen",
            "Fropie",
            "Canpetek",
            "Sakarkaya",
            "Emsal",
            "Melis",
            "Kaldera",
            "Berrak",
            "Nutella",
            "Ganik",
            "Richland",
            "Lotus",
            "Gold",
            "Noi",
            "Tukaş",
            "Burcu",
            "Chokella",
            "Crunch",
            "By İzzet",
            "Master Nut",
            "Schar",
            "Ülker",
            "Origin",
            "Weetabix",
            "Çokokrem",
            "Antebella",
            "Sinangil",
            "Abdurrahman Tatlıcı",
            "Şenocak",
          ],
        },
        "Temel Gıda": {
          "Sıvı Yağ": [
            "Komili",
            "Yudum",
            "Kristal",
            "Oneva",
            "Verde",
            "Sırma",
            "Orkide",
            "Tariş",
            "Anadolu Hazineleri",
            "Kırlangıç",
            "Güven Asa",
            "Çotanak",
            "Avofarm",
            "Turna",
            "Olitalia",
            "Nermin Hanım Zeytinliği",
            "Abalı",
            "Torku",
            "Marmarabirlik",
            "Hüner",
            "Asiltane",
          ],
          "Tuz, Baharat ve Harç": [
            "Bağdat",
            "Arifoğlu",
            "Knorr",
            "Reyondan",
            "Billur",
            "Efsina",
            "Ayfer Kaur",
            "Baharat Dünyası",
            "Dünya Hayat",
            "Salina",
            "Si&Ha",
            "Anadolu Lezzetleri",
            "Müsan",
            "Purelife",
            "Bizim",
            "Yayla",
            "Migros",
            "M Life",
            "City Farm",
            "Melis",
            "Tariş",
          ],
          Bulyon: ["Knorr", "Bizim", "Fide", "Veg & Bones", "Zel"],
          Konserve: [
            "Tat",
            "Dardanel",
            "Kühne",
            "Burcu",
            "Migros",
            "Superfresh",
            "Yayla",
            "Berrak",
            "İpek",
            "Fide",
            "Tamek",
            "Penguen",
            "Ant Bahar",
            "Reyondan",
            "Tukaş",
            "Gurme",
            "Öncü",
            "Melis",
            "Pınar",
            "Talia",
            "Tada",
            "Demko",
            "Kalite Tonla",
            "Yurt Konserve",
            "Sera",
            "Anadolu Lezzetleri",
            "Gurme212",
            "M Life",
          ],
          Sos: [
            "Kühne",
            "Calve",
            "Tat",
            "Fersan",
            "Heinz",
            "Migros",
            "Pınar",
            "Doğanay",
            "Knorr",
            "Tukaş",
            "Jr.Sous Chef",
            "Burcu",
            "Barilla",
            "Tabasco",
            "Tariş",
            "Uzman Kasap",
            "Hp",
            "Maille",
            "Remia",
            "Pastavilla",
            "Ferfresh",
            "Kikkoman",
            "Lowensenf",
            "Teptip",
            "Penguen",
            "King Crown",
            "Raz",
          ],
          Un: [
            "Söke",
            "Sinangil",
            "Eriş",
            "Migros",
            "Bemtat",
            "Bünsa",
            "İnci",
            "Anadolu Lezzetleri",
            "Güzel Ada Gıda",
            "Glutensiz Ada",
            "İstiklal Yolu",
            "Oneva",
            "M Life",
            "Schar",
            "Bağdat",
          ],
          Şeker: [
            "Migros",
            "Torku",
            "Irmak",
            "Bor Şeker",
            "Dr.Oetker",
            "Takita",
          ],
          "Sağlıklı Yaşam Ürünleri ": [
            "M Life",
            "Fellas",
            "Takita",
            "Doyum",
            "Züber",
            "Bio Protein",
            "Muscle Station",
            "Uniq2go",
            "Schar",
            "Orgalife",
            "Canderel",
            "City Farm",
            "Eti",
            "Tada",
            "Bemtat",
            "Sinangil",
            "Glutensiz Ada",
            "Güzel Ada Gıda",
            "Jr.Sous Chef",
            "Tchibo",
            "Delly",
            "Veggy",
            "Yayla",
            "Barilla",
            "Söke",
            "Saka",
            "Tat",
            "Powerade",
            "Bigjoy",
            "Kaldera",
            "Heinz",
            "Çaykur",
            "S.S. Tire Organik Gıda Kooperatifi",
            "The Lifeco",
            "Ant Bahar",
            "Huxol",
            "Anadolu Hazineleri",
            "Pastavilla",
            "Kristal",
            "Karali",
            "Kühne",
            "Calve",
          ],
        },
        "Meze, Hazır Yemek & Donuk": {
          Meze: [
            "Reyondan",
            "Gurumen",
            "Mezzetürk",
            "Beypazarı",
            "Biberes",
            "Mister No",
          ],
          "Paketli Sandviç": ["Tada", "Mister No", "Mr.No"],
          "Pratik Yemek": [
            "Yayla",
            "Knorr",
            "Tada",
            "Dardanel",
            "Zel",
            "Bizim",
            "Tat",
            "Gurmepack",
            "Yurt Konserve",
            "Tamek",
            "Burcu",
            "Veg & Bones",
            "Fide",
            "Veggy",
            "Gurme212",
            "Gurme",
            "G.C. Gıda",
            "Anadolu Lezzetleri",
            "Tukaş",
          ],
          "Dondurulmuş Gıda ": [
            "Superfresh",
            "Feast",
            "Muti Gıda",
            "Pınar",
            "Pek Food",
            "Lavi",
            "Embi",
            "Elmasoğlu",
            "Dr.Oetker",
            "Pizza Mi Go",
            "Galez",
            "Privegi",
            "Nelipide",
            "Veggy",
            "Yeşil",
            "Torpat",
            "Sarıvadi",
            "Toblerone",
            "Milka",
            "Başyazıcı",
            "Serez",
          ],
        },
        İçecek: {
          "Gazlı İçecek": [
            "Coca Cola",
            "Red Bull",
            "Pepsi",
            "Uludağ",
            "Schweppes",
            "Fanta",
            "Çamlıca",
            "Sprite",
            "Monster",
            "Yedigün",
            "Maltana",
            "Burn",
            "Coca-Cola",
            "Fruko",
            "Black Bruin",
            "Fever Tree",
            "Dydo",
            "Mountain Dew",
            "Beyoğlu Gazozu",
            "Joozy",
            "Seven Up",
            "Migros",
            "Peja",
            "Haliç Altın",
          ],
          "Gazsız İçecek": [
            "Dimes",
            "Cappy",
            "Tamek",
            "Migros",
            "Eker",
            "Elite Naturel",
            "Altınkılıç",
            "Uludağ",
            "Juss",
            "İçim",
            "Doğanay",
            "Sütaş",
            "Sek",
            "Danem",
            "The Good Wild",
            "Herby",
            "Pınar",
            "Serafresh",
            "Danone",
            "M Life",
            "Sarıyer",
            "Torku",
            "Kavaklıdere",
            "Arslan",
            "Vivo",
            "Orvital",
            "Serfresh",
            "Elta Ada",
            "High Five",
            "Balaban",
            "Vefa",
            "Pin",
            "DK",
            "Naturel",
            "Limmo",
            "Fo",
            "Tat",
          ],
          Çay: [
            "Lipton",
            "Doğadan",
            "Doğuş",
            "Migros",
            "Fuse Tea",
            "Çaykur",
            "Efor",
            "Herby",
            "Didi",
            "Ahmad Tea",
            "Si&Ha",
            "Teekanne",
            "Karali",
            "M Life",
            "Orgalife",
            "Tamek",
            "Dünya Hayat",
            "Pin",
            "Ofçay",
            "Pin Drinks",
            "Güzel Çay",
            "Juss",
            "Entschlackungstee",
            "Layaline",
          ],
          Kahve: [
            "Nescafe",
            "Tchibo",
            "Jacobs",
            "Starbucks",
            "Migros",
            "Cafe Crown",
            "Kurukahveci Mehmet Efendi",
            "Davidoff",
            "The Whirl",
            "İstanbul Kahve",
            "Dr.Oetker",
            "Obsesso",
            "Coffee Mate",
            "Lor",
            "Nesquik",
            "Cezbeli",
            "Kocatepe",
            "Kronotrop",
            "Lor Espresso",
            "Shazel",
            "Nestle",
            "Hisar Kahve",
            "Dripesso",
            "Zel",
            "Caffe Milano",
            "Cafe Time",
            "Danette",
            "Sütaş",
            "Sek",
            "Sahure Hanım",
            "My Coffee",
            "Tikveşli",
            "Coffee Time",
          ],
          Su: [
            "Erikli",
            "Pınar",
            "Nestle",
            "Damla",
            "Mila",
            "Saol",
            "Hayat",
            "Saka",
            "Uludağ",
            "Abant",
            "Assu",
            "Sırma",
            "Hamidiye",
            "Pürsu",
          ],
          "Maden Suyu": [
            "Sırma",
            "Frutti",
            "Damla",
            "Kızılay",
            "Saka",
            "Akmina",
            "San Pellegrino",
            "Pınar",
            "Kınık",
            "Uludağ",
            "Terme Di Crodo",
            "Migros",
            "Beypazarı",
            "Perrier",
          ],
        },
        Dondurma: {
          "Kap Dondurma": [
            "Carte d'Or",
            "Algida",
            "Mövenpick",
            "Golf",
            "Migros",
            "Bauvian",
            "Arzen",
            "Royal",
            "Viennetta",
            "Magnum",
            "Bravo",
          ],
          "Tek Dondurma": [
            "Magnum",
            "Bravo",
            "Algida",
            "Cornetto",
            "Max",
            "Koska",
            "Classics",
            "Eti",
            "Golf",
            "Migros",
            "Alaska Frigo",
            "Bounty",
            "Nogger",
            "Mars",
            "Roko",
            "Snickers",
            "Twix",
            "Frigola",
          ],
          Buz: ["Buzlat", "Icexperience"],
        },
        Atıştırmalık: {
          "Kuru Meyve": [
            "Reyondan",
            "Peyman",
            "Master Farm",
            "Tadım",
            "Dovido",
            "Asha",
            "Migros",
            "Otto Nuts",
            "By İzzet",
            "Emsal",
            "Quru",
            "Kırlıoğlu",
            "Noi",
            "Pol's",
            "M Life",
            "Kara Sevda",
            "Şenocak",
          ],
          "Kuru Yemiş": [
            "Reyondan",
            "Tadım",
            "Peyman",
            "Migros",
            "List Nuts",
            "Master Nut",
            "Kara Sevda",
            "Emsal",
            "Bobo",
            "By İzzet",
            "Fropie",
            "Şenocak",
            "Avuç Avuç",
            "Anadolu Lezzetleri",
            "Noi",
            "Çitliyo",
            "Bobo Nuts",
            "Siirt'ten",
          ],
          Cips: [
            "Doritos",
            "Lay's",
            "Çerezza",
            "Ruffles",
            "Cheetos",
            "Patos",
            "Çerezos",
            "Züber",
            "Patiswiss",
            "M Life",
            "Peyman",
            "Eti",
            "Vegeat's",
            "Chips Coin",
            "Pol's",
            "Chips Master",
            "Master",
            "Nutzz",
            "Cipso",
            "Bio Protein",
            "Anadolu Lezzetleri",
            "Reyondan",
          ],
          Çikolata: [
            "Eti",
            "Ülker",
            "Patiswiss",
            "Nestle",
            "Milka",
            "Tadelle",
            "Ozmo",
            "Godiva",
            "Lindt",
            "Kinder",
            "Elit",
            "Toblerone",
            "Torku",
            "Milango",
            "Damak",
            "Şölen",
            "Caramio",
            "M&M's",
            "Migros",
            "Maltesers",
            "Maitre Truffout",
            "Mcvitie's",
            "Albeni",
            "Çokokrem",
            "Lovells",
            "Toto",
            "Bonart",
            "Grand",
            "Schogetten",
            "Kahve Dünyası",
            "Toffifee",
            "Ferrero",
            "Ritter Sport",
            "Reyondan",
            "Jimmy",
            "Yupo",
          ],
          Gofret: [
            "Ülker",
            "Biscolata",
            "Eti",
            "Çizmeci Time",
            "9 Kat Tat",
            "Torku",
            "Nestle",
            "Tadelle",
            "Nutymax",
            "Boombastic",
            "Sarelle",
            "Luxens",
            "Dido",
            "Balocco",
            "Migros",
            "Kit Kat",
            "Ritter",
            "Kinder",
            "Mcvitie's",
            "Milka",
            "Çokonat",
            "Kahve Dünyası",
            "Alpella",
            "Ivorie",
            "Zeyrek",
          ],
          "Bar ve Kaplamalılar": [
            "Züber",
            "Eti",
            "Mixmey",
            "Ülker",
            "Fellas",
            "Patiswiss",
            "Nesfit",
            "Fropie",
            "Delly",
            "Albeni",
            "M Life",
            "Nestle",
            "Malty",
            "Twix",
            "Migros",
            "Peyman",
            "Cino",
            "Torku",
            "Metro",
            "Nesquik",
            "Corny",
            "Coco Star",
            "Snickers",
            "Piko",
            "Laviva",
            "Miskos",
            "Ozmo",
            "Bounty",
            "Mars",
            "Koska",
          ],
          Bisküvi: [
            "Eti",
            "Ülker",
            "Torku",
            "Oreo",
            "Biscolata",
            "Pötibör",
            "Migros",
            "Milka",
            "Halley",
            "Luppo",
            "Şölen",
            "Biskrem",
            "Mcvitie's",
            "Çokoprens",
            "Hanımeller",
            "Lotus",
            "Divan",
            "Altınbaşak",
            "İkram",
            "Annas",
            "Ozmo",
            "Aldiva",
            "Saklıköy",
            "Albeni",
            "Coco Star",
            "Weiss",
            "Patiswiss",
            "Leibniz",
            "Haylayf",
            "Lambertz Gingerbread",
            "Dankek",
            "Çizmeci Time",
            "Probis",
          ],
        },
        "Fırın & Pastane": {
          Ekmek: [
            "Reyondan",
            "Uno",
            "Unabella",
            "İhe",
            "Aly",
            "Mayaköy",
            "İyilik",
            "Hamurdan",
            "Backhaus",
            "Lavalia",
            "M Life",
          ],
          "Sabah Sıcakları": ["Unİstanbul", "Reyondan"],
          "Hamur ve Pasta Malzemeleri": [
            "Dr.Oetker",
            "Pakmaya",
            "Kenton",
            "Migros",
            "Ülker",
            "Altın",
            "Uno",
            "Bağdat",
            "Sinangil",
            "Kor",
            "Fo",
            "Bemtat",
            "Arifoğlu",
            "Unabella",
            "Balocco",
          ],
          "Yufka, Erişte ve Mantı": [
            "Mantı-ye",
            "Reyondan",
            "Bereket",
            "Myfresh",
            "Unabella",
            "Şahin",
          ],
          "Kuru Pasta": [
            "Alaçatı Ev Kurabiyecisi",
            "Reyondan",
            "Tatbak",
            "Myfırın",
            "Mardinden",
            "Hamurdan",
            "Uno",
            "İhe",
            "Anne Kalbi",
          ],
          Pasta: ["Reyondan", "Coquette", "Migros"],
          "Galeta, Grissini ve Gevrek": [
            "Eti",
            "Uno",
            "Wasa",
            "Migros",
            "Arı Grissini",
            "Unabella",
            "Hamurdan",
            "Reyondan",
            "Unİstanbul",
            "Altınbaşak",
            "Mayaköy",
            "Tatbak",
            "Anadolu Lezzetleri",
            "Balıkçıoğlu",
            "Arı",
            "Ülker",
          ],
          Tatlı: [
            "Dr.Oetker",
            "Pakmaya",
            "Kenton",
            "Reyondan",
            "Ege Glutensiz",
            "Saffet Abdullah",
            "Altın",
            "Hamurdan",
            "Kral",
          ],
        },
        "Deterjan & Temizlik": {
          "Çamaşır Yıkama": [
            "Bingo",
            "Migros",
            "Omo",
            "Yumoş",
            "Ariel",
            "Domestos",
            "Vernel",
            "Vanish",
            "Persil",
            "Perwoll",
            "Ace",
            "Frosch",
            "Alo",
            "Renax",
            "Peros Matik",
            "Rinso",
            "Just Green",
            "Duru",
            "Lysol",
            "Tursil",
            "Calgon",
            "Marc",
            "Aquabor",
            "Peros",
            "K2R",
            "Ernet",
          ],
          "Bulaşık Yıkama": [
            "Finish",
            "Fairy",
            "Pril",
            "Migros",
            "Frosch",
            "Just Green",
            "Turmepa",
            "Bingo",
            "Peros",
          ],
          "Genel Temizlik": [
            "Cif",
            "Porçöz",
            "Glade",
            "Migros",
            "Mr Muscle",
            "Domestos",
            "Ernet",
            "Airwick",
            "Bref",
            "Green World",
            "Sitil",
            "Camsil",
            "Yumoş",
            "Asperox",
            "Mr.Muscle",
            "Frosch",
            "Bingo",
            "Ace",
            "Pereja",
            "Cillit Bang",
            "Raid",
            "Nazar",
            "Vanish",
            "Pronto",
            "Febreze",
            "Newo",
            "Clonet",
            "Selsil",
            "Jet",
            "Marc",
            "Luur",
            "Just Green",
            "Bion",
            "Shine Bloom",
            "Ajax",
            "Dixi",
            "Asprin",
            "Clin",
            "Odorfin",
            "Lysol",
            "Defans",
            "Turmepa",
            "Farell",
            "Parex",
            "Fairy",
            "Goddards",
            "Feat",
            "Tukaka",
          ],
          "Temizlik Malzemeleri": [
            "Parex",
            "Macromax",
            "Koroplast",
            "Bella",
            "A-plex",
            "Scotch Brite",
            "Roll-Up",
            "Migros",
            "Sleepy",
            "Klen Hauss",
            "Solo",
            "Flex",
            "Reyondan",
            "Turco",
            "A Plex",
            "Next Bio",
            "Proff",
            "Banat",
            "Next",
            "Mr Oxy",
            "Familia",
          ],
          "Banyo Gereçleri": [
            "Mistique Home",
            "Leva",
            "Evvon",
            "Bee Home",
            "Bosphorus",
            "Farist Home",
            "Reyondan",
            "Koopman",
            "Bestchoice",
            "Evmoni",
            "Farist Bath",
            "Keramika",
            "Lova",
            "Viamart",
          ],
          "Çamaşır Gereçleri": [
            "Command",
            "Perilla",
            "Leva",
            "Magic Saver",
            "Ege",
            "Mistique Home",
            "Granit",
            "3M",
            "Ckc",
            "Huub",
            "Bee Home",
            "Bestchoice",
            "Evvon",
            "Sia",
            "Boss Tape",
            "Yıldız",
            "Lady",
            "Qlux",
            "Touch Me",
            "My Hanger",
            "Viamart",
          ],
          "Çöp Poşeti": [
            "Koroplast",
            "Cook",
            "Migros",
            "İdeal",
            "Macromax",
            "Astra",
          ],
          "Özel Paketler": ["Parex"],
        },
        "Kağıt ve Islak Mendil": {
          "Islak Mendil": [
            "Uni Baby",
            "Sleepy",
            "Prima",
            "Selpak",
            "Minies",
            "Molfix",
            "Migros",
            "Dalin",
            "Activex",
            "Hops",
            "Komili",
          ],
          "Tuvalet Kağıdı": [
            "Papia",
            "Sofia",
            "Selpak",
            "Familia",
            "Solo",
            "Viva",
            "Mare",
            "Ecco Soft",
            "Ecco",
            "Maylo",
            "Minies",
          ],
          "Kağıt Havlu": [
            "Sofia",
            "Solo",
            "Selpak",
            "Maylo",
            "Papia",
            "Familia",
            "Mare",
            "Ecco",
            "Viva",
            "Migros",
            "Ecco Soft",
          ],
          Peçete: [
            "Selpak",
            "Duni",
            "Solo",
            "Sofia",
            "Familia",
            "Viva",
            "Dunilin",
            "Servis",
            "Migros",
            "Ecco",
            "Maylo",
          ],
          "Kağıt Mendil": [
            "Selpak",
            "Sofia",
            "Maylo",
            "Kleenex",
            "Komili",
            "Viva",
          ],
        },
        "Kişisel Bakım, Kozmetik &  Sağlık": {
          "Güneş Bakım": [
            "Cireaseptine",
            "Nivea",
            "Wemara",
            "Beeo",
            "Mara",
            "Carroten",
            "Sebamed",
            "Minela Care",
            "Eda Taşpınar",
          ],
          "Hijyenik Ped": [
            "Orkid",
            "Kotex",
            "Molped",
            "Sleepy",
            "O.B",
            "Carefree",
            "Migros",
            "Tampax",
            "Deep Fresh",
          ],
          "Ağız Bakım Ürünleri": [
            "Colgate",
            "Oral-B",
            "Sensodyne",
            "Signal",
            "Difaş",
            "Banat",
            "Listerine",
            "Parodontax",
            "Biomed",
            "Ipana",
            "Rocs",
            "Pearl Drops",
            "Corega",
            "Piknik",
            "Dermokil",
            "Fixodent",
            "Migros",
            "Himalaya",
            "T-brush",
            "Stopever",
          ],
          "Saç Bakım Ürünleri": [
            "L'Oreal Paris",
            "Pantene",
            "Elidor",
            "Garnier",
            "Palette",
            "Head&Shoulders",
            "Gliss",
            "Koleston",
            "Urban Care",
            "Difaş",
            "Clear",
            "Hobby",
            "OGX",
            "Banat",
            "Herbal Essences",
            "Dove",
            "John Frieda",
            "Viored",
            "Egos",
            "Tints Of Nature",
            "Blendax",
            "Tresan",
            "Syoss",
            "Taft",
            "Sebamed",
            "Bioblas",
            "Just For Men",
            "Revox",
            "Cosnature",
            "Men Perfect",
            "Ziaja",
            "Dp",
            "Restorex",
            "Flamingo",
            "Dermokil",
            "Dax",
            "Wemara",
            "Eder",
            "Mixup",
            "Morfose",
            "Lionesse",
            "Ambiente",
          ],
          "Duş, Banyo ve Sabun": [
            "Palmolive",
            "Duru",
            "Le Petit Marseillais",
            "Dove",
            "Dalan",
            "Hacı Şakir",
            "Balmy Naturel",
            "Migros",
            "Savon De Royal",
            "Old Spice",
            "Peros",
            "Protex",
            "Fax",
            "Pereja",
            "Sleepy",
            "Activex",
            "Johnson's Baby",
            "Soho NYC",
            "Deep Fresh",
            "The Soap Factory",
            "Olivos",
            "Nivea",
            "Mara",
            "Just Green",
            "Dermokil",
            "Kırlangıç",
            "Sebamed",
            "Frosch",
            "Head&Shoulders",
            "L'Oreal Paris",
            "Turmepa",
            "Loofah",
          ],
          "Tıraş Malzemeleri": [
            "Gillette",
            "Arko",
            "Derby",
            "Bic",
            "Nivea",
            "Permatik",
            "Just For Men",
          ],
          "Ağda ve Epilasyon": [
            "Veet",
            "Vi-Vet",
            "Gillette Venus",
            "Remove",
            "Gillette",
            "Bic",
            "Like Me",
            "Balmy Naturel",
            "Lionesse",
            "Derby",
            "Jolly",
            "Promani",
            "Banat",
          ],
          "Cilt Bakımı": [
            "Nivea",
            "Neutrogena",
            "L'Oreal Paris",
            "Arko",
            "Bepanthol",
            "Garnier",
            "Himalaya",
            "Cireaseptine",
            "Dr.Smart",
            "Dermokil",
            "Mara",
            "Sebamed",
            "Beeo",
            "Maruderm",
            "Simple",
            "Tonymoly",
            "Ziaja",
            "Bio-Oil",
            "Like Me",
            "Voop",
            "Siveno",
            "Krauterhof",
            "Hobby",
            "Claderm",
            "Vaseline",
            "Altermed",
            "Mixup",
            "Johnson's Baby",
            "Maybelline New York",
            "Eda Taşpınar",
            "Uni Care",
            "Tomy",
            "Flormar",
            "Talya",
            "Botanica",
            "Stopever",
          ],
          Kolonya: [
            "Selin",
            "Pereja",
            "Duru",
            "Johnson's Baby",
            "Migros",
            "Önder",
            "Boğaziçi",
            "Rebul",
          ],
          "Parfüm, Deodorant": [
            "Nivea",
            "Rexona",
            "Emotion",
            "Garnier",
            "Blade",
            "Old Spice",
            "Axe",
            "Dreamland",
            "L'Oreal Paris",
            "Fa",
            "Privacy",
            "Antonio Banderas",
            "Dove",
            "Mara",
            "Deotak",
            "Lolita",
            "Eda Taşpınar",
            "Aqua Di Polo",
            "Ossia",
            "Bellisima",
            "First Class",
            "Beeo",
            "Cireaseptine",
            "Pereja",
            "Siveno",
            "Sebamed",
          ],
          Makyaj: [
            "Maybelline New York",
            "Golden Rose",
            "Flormar",
            "Essence",
            "L'Oreal Paris",
            "Pastel",
            "Note",
            "Mara",
            "Garnier",
            "Mixup",
            "Nivea",
            "Lüx",
            "Like Me",
            "Lush Lash",
            "Şelale",
            "İpek",
            "Neutrogena",
            "Johnson's Baby",
            "Nascita",
            "Cotoneve",
            "Cotton Soft",
            "Cle Up",
            "Flamingo",
            "Color Tattoo",
          ],
          "Sağlık Ürünleri": [
            "Durex",
            "Talya",
            "Okey",
            "Canped",
            "Nature's Supreme",
            "Arifoğlu",
            "Voop",
            "Tabanex",
            "Getwell",
            "Lionesse",
            "Naturagen",
            "Ülker",
            "Stopever",
            "One Up",
            "Depend",
            "Vitago",
            "Sleepy",
            "Silky Kiss",
            "Boos+",
            "The Lifeco",
            "Banat",
            "Neutrogena",
            "Prosafe",
            "İpek",
            "Vitagil",
            "Dr.Plus",
            "Süper Süzen",
            "Qlife",
            "Beeo",
            "Önce",
            "Lüx",
            "Promani",
            "Breathe Right",
            "Mara",
            "Johnson's Baby",
            "Cotton Soft",
            "Migros",
            "Cle Up",
            "Balmy Naturel",
            "Vlamor",
            "Bepanthol",
            "Tonymoly",
            "Cireaseptine",
            "Nascita",
            "Triogermila-ı",
            "Alvin",
          ],
          "Özel Paketler": ["Wemara"],
        },
        Bebek: {
          "Bebek Bezi": [
            "Prima",
            "Sleepy",
            "Molfix",
            "Minies",
            "Goo.n",
            "Huggies",
            "Goon",
            "Canped",
          ],
          "Bebek Bakım": [
            "Dalin",
            "Johnson's Baby",
            "Bepanthol",
            "Uni Baby",
            "Chicco",
            "İpek",
            "Wee Baby",
            "Mycey",
            "Dentavit",
            "Sudocrem",
            "Sebamed",
          ],
          "Bebek Beslenme": [
            "Hipp",
            "Wee Baby",
            "Bebelac",
            "Aptamil",
            "Sma",
            "Humm",
            "Hero Baby",
            "Gerber",
            "Milupa",
            "Veg & Bones",
            "Chicco",
            "Arılac",
            "Arı",
          ],
          "Bebek Banyo": [
            "Johnson's Baby",
            "Dalin",
            "Uni Baby",
            "Sebamed",
            "Johnsons&Johnsons",
            "Komili",
            "Bepanthol",
            "Balmy Naturel",
            "Minies",
          ],
          "Bebek Deterjanı ve Yumuşatıcı": [
            "Uni Baby",
            "Dalin",
            "Omo",
            "Yumoş",
            "Roxy",
            "Frosch",
            "Dalan",
            "Hacı Şakir",
            "Minies",
          ],
          "Bebek Tekstil": ["Kardelen"],
          "Anne Ürünleri": ["Lactamil", "Doğadan"],
        },
        "Ev & Yaşam": [
          "Mutfak Eşyaları",
          "Mobilya ve Dekorayon",
          "Bahçe ve Piknik Malzemeleri",
          "Spor ve Outdoor",
          "Ev Tekstili",
          "Giyim",
        ],
        "Kitap, Kırtasiye & Oyuncak": [
          "Kitap, Dergi ve Gazete",
          "Kırtasiye",
          "Oyuncak",
        ],
        Çiçek: ["Canlı Bitki", "Yapay Çiçek"],
        "Pet Shop": ["Köpek", "Kedi", "Kuş", "Pet Aksesuarları"],
        Elektronik: [
          "Telefon ve Aksesuarları",
          "Bilgisayar ve Aksesuarları",
          "Beyaz Eşya",
          "Elektrikli Ev Aletleri",
          "Oyun Konsolları",
          "Görüntü ve Ses Sistemleri",
          "Hobi ve Eğlence",
        ],
      },
      selectItemKey: "",
      itemValues: "",
      selectItemValue: "",
    };
  },
  watch: {
    date: function (date) {
      this.dateFormat = `${date.getDate()}.${
        date.getMonth() + 1
      }.${date.getFullYear()}`;
    },
  },
  methods: {
    dateClose() {
      this.datePickers = !this.datePickers;
    },
    itemValuesFunction() {
      this.selectItemValue = "";
      for (const iterator of Object.entries(this.items)) {
        if (iterator[0] == this.selectItemKey) {
          return (this.itemValues = iterator[1]);
        }
      }
    },
  },
};
</script>


<style>
.v-picker__header,
.v-picker-title,
.v-input__details {
  display: none !important;
}
</style>